version: '3'

volumes: {}

services:

  oereb-server:
    networks:
    - default
    build: .
    image: sitj/jura-crdppf-v2
    environment:
    - PRINT_SERVICE_HOST=oereb-print
    - PRINT_SERVICE_PORT=8080
    - PGHOST=172.17.0.1
    - PGDATABASE=${PGDB:-pyramid_oereb}
    - PGPORT=${PGPORT:-5432}
    - PGUSER=${PGUSER:-www-data}
    - PGPASSWORD=${PGPASSWORD:-www-data}
    - OEREB_SERVER_ROUTE_PREFIX
    - BASE_HOST
    - PDF_ARCHIVE_PATH
    ports:
    - ${EXTERNAL_PORT}:8080
    volumes:
    - ${PDF_ARCHIVE_PATH}:${PDF_ARCHIVE_PATH}:rw
    - /var/www/vhosts/sitj/logs:/var/log/host_apache_logs
    - /etc/localtime:/etc/localtime:ro

  oereb-print:
    mem_limit: 2G
    image: sitj/jura-crdppf-print-v2:latest
    networks:
     - default
    environment:
      PRINT_YAML_MAX_ALIASES: 200
      LOG_LEVEL: INFO
      CATALINA_OPTS: >-
        -Xmx512M
    volumes:
      - ./print/print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro

  oereb-client:
    build:
        context: client
    image: sitj/oereb-client
    environment:
    - OEREB_CLIENT_ROUTE_PREFIX
    - OEREB_SERVICE_URL
    - AVAILABILITY_URL
    - SEARCH_URL
    ports:
    - ${EXTERNAL_PORT_CLIENT}:8080
    volumes:
    - ./client/config:/app/config
    restart: always

