version: '3'

volumes: {}

services:

  oereb-server:
    networks:
    - default
    build: .
    image: camptocamp/jura-crdppf-v2
    environment:
    - PRINT_SERVICE_HOST=print
    - PRINT_SERVICE_PORT=8080
    - PGHOST=${PGHOST:-172.17.0.1}
    - PGDATABASE=${PGDB:-pyramid_oereb}
    - PGPORT=${PGPORT:-5432}
    - PGUSER=${PGUSER:-www-data}
    - PGPASSWORD=${PGPASSWORD:-www-data}
    - OEREB_ROUTE_PREFIX
    ports:
    - ${EXTERNAL_PORT}:8080
    volumes:
    - /archive:/archive:rw
    - /var/www/vhosts/sitj/logs:/var/log/host_apache_logs
    - /etc/localtime:/etc/localtime:ro

  oereb-print:
    mem_limit: 2G
    image: camptocamp/mapfish_print:3.28.1
    networks:
     - default
    environment:
      PRINT_YAML_MAX_ALIASES: 200
      LOG_LEVEL: INFO
      CATALINA_OPTS: >-
        -Xmx512M
    volumes:
      - ./print-apps:/usr/local/tomcat/webapps/ROOT/print-apps:ro
