oereb_client:

  # Application configuration
  # Mandatory:
  #   "title" - The multilingual application title
  #   "logo_canton" - Multilingual URL of the cantonal logo
  #   "languages" - List of the available languages
  #   "default_language" - The language used as default
  # Optional:
  #   "icon" - URL to image used as favicon
  #   "logo_oereb" - Multilingual URL of the oereb logo
  #   "local_storage_prefix" - Prefix used for the local browser storage
  application:
    title:
      - Language: fr
        Text: CRDPPF Jura
    icon: views/static/favicon.ico
    logo_canton:
      - Language: fr
        URL: views/static/logo_jura.png
    logo_oereb:
      - Language: fr
        URL: views/static/logo_oereb_fr.png
    local_storage_prefix: oereb_ju
    languages:
      - fr
    default_language: fr

  # View configuration
  view:
    map_x: 2580387
    map_y: 1242892
    map_zoom: 1
    resolutions: [140, 70, 26.5, 14, 7, 3.5, 2.65, 1.75, 1.3, 0.7, 0.35, 0.2, 0.1, 0.05]

  # Base layer configuration
  base_layer:
    type: wmts
    url: https://geo.jura.ch/tiles/1.0.0/WMTSCapabilities.xml
    layer: sdt_01_03_mensuration_officielle
    matrixSet: swissgrid
    projection: "EPSG:2056"
    style: default
    format: image/png

  # Availability layer
  availability:
    url: !ENV ${AVAILABILITY_URL}
    params:
      LAYERS: oereb_published_municipalities
      FORMAT: image/png

  service_url: !ENV ${OEREB_SERVICE_URL}

  # Search configuration
  search:
##    - title:
##        - Language: fr
##          Text: E-GRID
##      url: !ENV ${SEARCH_URL}
##      params:
##        limit: 5
##        prefix: egr
##      hook_method: jura_crdppf_client.views.search.hook_egrid
##      verify_certificate: False
    - title:
        - Language: fr
          Text: Adresse
      url: !ENV ${SEARCH_URL}
      params:
        limit: 5
        prefix: adr
      hook_method: jura_crdppf_client.views.search.hook_address
      verify_certificate: False
    - title:
        - Language: fr
          Text: Parcelle / EGRID
      url: !ENV ${SEARCH_URL}
      params:
        limit: 5
        prefix: parcel
      hook_method: jura_crdppf_client.views.search.hook_real_estate
      verify_certificate: False

  # Link to external viewer/portal
  external_viewer:
    tooltip:
      - Language: fr
        Text: Aller sur le géoportail cantonal
    url: https://geo.jura.ch
    params:
      - "wfs_layer=sdt_01_04_md_sit_bf_interrogation"
      - "wfs_egris_egrid={egrid}"
      - "no_redirect="
      - "theme=Cadastre RDPPF"
#      - "tree_groups=CRDPPF"
#      - "tree_groups=Bau- und Strassenlinien,Kataster belasteter Standorte,Lärm,Nutzungsplan"
#      - "tree_group_layers_Bau- und Strassenlinien=statische_waldgrenzen,baulinien_kommunal_waldabstandslinien,baulinien_kommunal,baulinien_kantonal"
#      - "tree_group_layers_Kataster belasteter Standorte=kbs_kataster_standorte"
#      - "tree_group_layers_Lärm=laermempfindlichkeitsstufen"
#      - "tree_group_layers_Nutzungsplan=nutzungsplanung_kantonal_grundnutzung_group,nutzungsplanung_kommunal_grundnutzung_group,nutzungsplanung_kantonal_ueberlagernd_rechtsverbindlich_group,nutzungsplanung_kommunal_ueberlagernd_rechtsverbindlich_group,nutzungsplanung_kantonal_perimeter_tiefbau_umrandung,nutzungsplanung_kommunal_sondernutzungsplan_umrandung"

  # Support
  support:
    office1:
      - Language: fr
        Text: Canton du Jura
    office2:
      - Language: fr
        Text: Section du cadastre et de la geoinformation
    street: Rue du 24-Septembre
    city: 2800 Delémont
    email: sit@jura.ch
    phone: +41 32 420 53 10

  user_guide: https://geo.jura.ch/doc/Aide/Aide_CRDPPF.pdf

  # Custom CSS file
  custom_css_url: views/static/custom.css

  # Enable Google Analytics by specifying account key
  # google_analytics:
